### ISSUE TITLE
Applicant Evaluation system

### ISSUE THREAD

**Issue by arshiya-singh** [HackGT/registration#154]
come up with a customizable evaluation system (an upgrade from accepting/rejecting). User can add in any criteria with any value type (e.g. rating with a scale of 1 - 5, interview needed with T/F, type of interview, etc.)

**Comment by bunsenmcdubbs** [comment]
I like this idea but I think it should go into a separate application that will eventually hook into registration (similar to the plan for checkin).

**Comment by petschekr** [comment]
Fixed by our Slack bot https://github.com/HackGT/application-bot
