### ISSUE TITLE
Misconfigured Google Authentication callback

### ISSUE THREAD

**Issue by BunsenMcDubbs** [HackGT/registration#20]
Signing in with Google redirects to `localhost:3000` rather than the actual domain.
<img width="827" alt="screen shot 2017-02-26 at 12 09 11 pm" src="https://cloud.githubusercontent.com/assets/699273/23342260/b7291c70-fc1c-11e6-9daa-4aef69bcb433.png">

**Comment by illegalprime** [comment]
This was fixed in #19 , thanks for reporting though.
