### ISSUE TITLE
Dashboard page

### ISSUE THREAD

**Issue by petschekr** [HackGT/registration#21]
We need some kind of dashboard page with information similar to what the [HackMIT registration](https://github.com/HackGT/hackmit-registration-preview/blob/master/app/client/views/dashboard/dashboard.html) dashboard had.

**Comment by ganhari123** [comment]
Hey So i added some stuff and pushed my changes to a new branch. There are some database stuff that have to be changed, unfortunately I have some other work due tomorrow so I have to finish that, but take a look at schema.ts and index.html to see the changes that I have made.
