### ISSUE TITLE
Dashboard as a timeline

### ISSUE THREAD

**Issue by ehsanmasdar** [HackGT/registration#215]
Alter the dashboard to show a more timeline-like view of user status to help the user understand where they are in the application process.
Include these states:
1. Applying
2. Pending Decision
3. Confirming `Branch Name` (This could be Rejected or Confirming `Waitlist`)
4. Confirmed
5. Prompt to form team (Optional)

This is pretty easy after changes in #214, which has server-side logic to determine the user's current state.

**Comment by cchu70** [comment]
Are we also including team formation after the "Confirmed" status?

**Comment by ehsanmasdar** [comment]
@cchu70 I like the idea of prompting team formation 👍 . Added to the issue.
