### ISSUE TITLE
Add a legend in the admin screen

### ISSUE THREAD

**Issue by bunsenmcdubbs** [HackGT/registration#39]
As admin, viewing a list of all users, I see stars and checkmarks next to user emails. I assume:
 - stars = admins
 - checkmarks = confirmed user? submitted application?

There should be a small legend at the top/side so its more explicit.

**Comment by petschekr** [comment]
The stars are admins and the checkmarks indicate verified emails. You're right though that it should be clearer what those symbols mean.
