### ISSUE TITLE
Create the success and failure pages.

### ISSUE THREAD

**Issue by illegalprime** [HackGT/registration#4]
We need pages that represent:

1. a response being successfully recorded on the server
2. a server failure

these will be served after the user submits the registration.

**Comment by petschekr** [comment]
Resolved by https://github.com/HackGT/registration/blob/master/client/js/application.ts#L16?

**Comment by BunsenMcDubbs** [comment]
@petschekr That's what it looks like 👍

**Comment by petschekr** [comment]
Cool, I'll close this then
