### ISSUE TITLE
Navigation to/between applications

### ISSUE THREAD

**Issue by bunsenmcdubbs** [HackGT/registration#43]
When there are multiple applications (aka our case with student, mentor, and chaperone), we should add in certain UI tweaks to make it friendlier.

1. **[Beginner Friendly]** Let users go back to the "Choose what you want to apply as" screen. Yes, they can just go back in their browser but that's not always intuitive (also what if you clicked a link...)

2. **[Not as beginner friendly]** Enable "deep linking" aka allow someone to be linked directly to a specific application.
Use case:
   1. A mentor link would be `https://registration.hack.gt/apply/mentor`
   2. New user would be redirected to a login/signup screen
   3. When authenticated, they are navigated directly to the mentor application (rather than dashboard or generic application screen)

**Comment by BunsenMcDubbs** [comment]
[express-deep-link](https://github.com/lanetix/express-deep-link) looks like a good solution to this. Problems:
1. Kinda old repository (not updated in 2 years, some deprecated dependencies)
2. No typescript typings (+ strict mode in our `tsconfig.json`)
