### ISSUE TITLE
Support file uploads in form

### ISSUE THREAD

**Issue by bunsenmcdubbs** [HackGT/registration#46]
This one is going to be tricky (not _too bad_, just harder than the other form fields)... We need to be able to support file uploads in the application form. Development for this can come in 2 stages.

**First, support file uploads and save to disk.**
 - configure a location on disk to save files (absolute or relative path - absolute is encouraged for production, relative makes it easier for development)
 - save user's file uploads in a directory structure inside the uploads directory that supports multiple file upload fields
ex) `uploads/<question1/question2/question3>/<user_id>.<file_ext>`
 - any API requests for getting application/user data should indicate that the user has a file uploaded for that field but not include the file itself. Create a separate endpoint for file uploads.
ex) (and this is a totally wild guess, please change as appropriate) `GET /api/files/<question_id>/<user_id>`

There are several considerations for this approach:
 - Questions now need id's (or some identification method to support multiple file upload fields in a form)
 - how to support multiple files for a single field? zip all files when downloading on `GET` requests? consider changing directory structure to:
`uploads/<question_id>/<user_id>/<file_name>`

**The second stage will be considerably... fancier.** Modularize/decouple the actual file upload handling process. ex) What if you don't want to upload to a local directory? Enable "pluginability" (upload to S3, Google Drive API etc.)?

**Comment by petschekr** [comment]
Basic file uploading is already implemented (they get put in the `uploads` directory but I like a lot of the other ideas here. Also, questions already have a sort of ID in the form of the `name` attribute which has to be unique for each question and isn't shown to the user.
