### ISSUE TITLE
Accepted RSVP / question form

### ISSUE THREAD

**Issue by petschekr** [HackGT/registration#49]
Accessed after being accepted to confirm attending the event

Blocked by #48

**Comment by petschekr** [comment]
Some sort of send out acceptances button should be put at the bottom of the section added in #60

**Comment by BunsenMcDubbs** [comment]
@petschekr By evaluation form you mean a form that the accepted user needs to fill out to RSVP right? Our specific use includes evaluation questions but in general this is a "confirmation" or "RSVP" form.

**Comment by petschekr** [comment]
@BunsenMcDubbs Yeah that's what I meant. I'll change the title of this issue.
