### ISSUE TITLE
Define all question primitives, load text configuration into JSON.

### ISSUE THREAD

**Issue by illegalprime** [HackGT/registration#6]
Define all the types of questions you can ask, some ideas are:

1. `text`
2. `phone-number`
3. `select` or `combo`
4. `date`
5. `url`
6. `file`
7. `unique-select` or `radio`

along with these definitions make a [JSON schema](http://json-schema.org/) for the file and provide some code to load the configuration file, check it against a schema, and return a JSON object.

**Comment by Anish2** [comment]
#10
