### ISSUE TITLE
Strategically Place Logs

### ISSUE THREAD

**Issue by illegalprime** [HackGT/registration#73]
We want to log when the user does **anything**, then we can look back and see some trends and even do some AB testing! I'd like to use this issue to make sure everyone has a voice on what they want tracked.

cc @petschekr @bunsenmcdubbs 

What I'm thinking so far:
 - [x]  visiting
 - [x] creating an account
 - [x] starting registration
 - [x] completing registration

And what to log:
 - [ ] any demographic information available
 - [x] a unique identification when available
 - [x] time
 - [x] location

Anyone else have any other ideas? Assigning @kexin-zhang on this since she's the master of metrics!

**Comment by kexin-zhang** [comment]
I've got some basic logs printing out in c06e8970b2859d195414706d9bda5b2964bf13ab. Any thoughts on how to go about getting location? IP Address?

**Comment by bunsenmcdubbs** [comment]
IP Address might be our best bet but that could be tricky. Oftentimes the web app is too high in the stack to (easily) get any information about IP address or it is spoofed/omitted/inconsistently represented.

Might be worth punting on location for now. @illegalprime thoughts?

**Comment by petschekr** [comment]
If we can get the router / reverse proxy to pass along IP information in `X-Forwarded-*` headers, you can access it from Express by running `app.enable('trust proxy');` (when in production) and getting it from [`request.ip`](https://expressjs.com/en/4x/api.html#req.ip).

**Comment by kexin-zhang** [comment]
Thanks @petschekr and @bunsenmcdubbs! I'm going to go ahead with `request.ip`

**Comment by illegalprime** [comment]
We also have this: https://developer.mozilla.org/en-US/docs/Web/API/Geolocation/Using_geolocation

**Comment by bunsenmcdubbs** [comment]
now that #76 has been merged, is this issue closed?
