### ISSUE TITLE
Add machine parse-able tags for important questions. 

### ISSUE THREAD

**Issue by illegalprime** [HackGT/registration#97]
Soon we'll want to look up people's school name (like for the sponsor portal). We might want to tag each question with a well-known tag like 'school' or 'dietary'. Thoughts?

**Comment by bunsenmcdubbs** [comment]
Is existing question metadata insufficient? Each question has a `name` field... https://github.com/HackGT/registration/blob/master/server/config/questions.json

**Comment by illegalprime** [comment]
@bunsenmcdubbs yeah that looks good. I think an API with that + listing all the names would be good.
